### ISSUE TITLE
cres-app basic structure

### ISSUE THREAD

**Issue by JitenPalaparthi** [JitenPalaparthi/cres_app#5]

**Comment by JitenPalaparthi** [comment]
> Colour combinations
> Logos
> Icons
> Themes
> Menus
> Drawer Menus

**Comment by JitenPalaparthi** [comment]
@Sindhu create an app and push to the repo.It  can be an empty app

**Comment by JitenPalaparthi** [comment]
flutter creare cres_app
cd cres_app
git init
git add *
git commit -m "add initial structure"
git branch -M main
git remote add origin git@github.com:JitenPalaparthi/cres-app.git

git checkout -b #5

git push -u origin#5

**Comment by Sindhu-hub14** [comment]
done
